name: Update all config files on merge from dev to main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-configs:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        
    - name: Install jq
      run: sudo apt-get install -y jq
      
    - name: Update mta.yaml
      run: |
        if [ -f "mta.yaml" ]; then
          sed -i 's/actions/actionsdev/g' mta.yaml
          echo "mta.yaml updated"
        else
          echo "mta.yaml not found"
        fi
        
    - name: Update xs-security.json
      run: |
        if [ -f "xs-security.json" ]; then
          sed -i 's/"actions"/"actionsdev"/g' xs-security.json
          jq empty xs-security.json
          echo "xs-security.json updated and validated"
        else
          echo "xs-security.json not found"
        fi
        
    - name: Update manifest.json
      run: |
        if [ -f "webapp/manifest.json" ]; then
          sed -i 's/"actions"/"actionsdev"/g' webapp/manifest.json
          jq empty webapp/manifest.json
          echo "manifest.json updated and validated"
        else
          echo "webapp/manifest.json not found"
        fi
        
    - name: Update package.json
      run: |
        if [ -f "package.json" ]; then
          sed -i 's/"actions"/"actionsdev"/g' package.json
          jq empty package.json
          echo "package.json updated and validated"
        else
          echo "package.json not found"
        fi
        
    - name: Update ui5.yaml
      run: |
        if [ -f "ui5.yaml" ]; then
          sed -i 's/actions/actionsdev/g' ui5.yaml
          echo "ui5.yaml updated"
        else
          echo "ui5.yaml not found"
        fi
        
    - name: Update xs-app.json
      run: |
        if [ -f "xs-app.json" ]; then
          sed -i 's/"actions"/"actionsdev"/g' xs-app.json
          jq empty xs-app.json
          echo "xs-app.json updated and validated"
        else
          echo "xs-app.json not found"
        fi
        
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated update: replaced actions with actionsdev in config files after merge"
          git push
        fi
