name: Update all config files on merge from dev to main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-configs:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        
    - name: Install jq
      run: sudo apt-get install -y jq
      
    - name: Update mta.yaml (IDs específicos)
      run: |
        if [ -f "mta.yaml" ]; then
          # Reemplazar IDs de aplicación pero no otros usos de "actions"
          sed -i 's/\(id\|name\|service\): actions$/\1: actionsdev/' mta.yaml
          sed -i 's/\(id\|name\|service\): "actions"$/\1: "actionsdev"/' mta.yaml
          echo "mta.yaml updated"
        else
          echo "mta.yaml not found"
        fi
        
    - name: Update xs-security.json (IDs específicos)
      run: |
        if [ -f "xs-security.json" ]; then
          jq 'walk(if type == "object" then 
                with_entries(if .key | test("^(id|name|service)$") then 
                  .value |= (if type == "string" then gsub("^actions$"; "actionsdev") else . end) 
                else . end) 
              else . end)' xs-security.json > tmp.json && mv tmp.json xs-security.json
          echo "xs-security.json updated"
        else
          echo "xs-security.json not found"
        fi
        
    - name: Update manifest.json (versión robusta)
      run: |
        if [ -f "webapp/manifest.json" ]; then
          jq 'walk(
            if type == "object" then
              with_entries(
                .value |= (
                  if type == "string" then
                    if . == "actions" then "actionsdev"
                    elif test("^actions\\.") then sub("^actions\\."; "actionsdev.")
                    elif test("^RouteActions") then sub("^RouteActions"; "RouteActionsdev")
                    elif test("^Actions") then sub("^Actions"; "Actionsdev")
                    elif test("^actions\\.view") then sub("^actions\\.view"; "actionsdev.view")
                    else . end
                  else . end
                )
              )
            else . end
          )' webapp/manifest.json > tmp.json && mv tmp.json webapp/manifest.json
          echo "manifest.json updated successfully"
        else
          echo "webapp/manifest.json not found"
          exit 0
        fi
        
    - name: Update package.json (IDs específicos)
      run: |
        if [ -f "package.json" ]; then
          jq ' 
            .name |= sub("^actions$"; "actionsdev") |
            .scripts |= with_entries(
              .value |= (
                if type == "string" then
                  # Solo reemplaza "actions" si NO está seguido de "dev"
                  gsub("actions(?!dev)"; "actionsdev")
                else . end
              )
            )
          ' package.json > tmp.json && mv tmp.json package.json
          echo "package.json updated"
        else
          echo "package.json not found"
        fi


        
    - name: Update ui5.yaml (IDs específicos)
      run: |
        if [ -f "ui5.yaml" ]; then
          sed -i 's/\(id\|name\|service\): actions$/\1: actionsdev/' ui5.yaml
          sed -i 's/\(id\|name\|service\): "actions"$/\1: "actionsdev"/' ui5.yaml
          echo "ui5.yaml updated"
        else
          echo "ui5.yaml not found"
        fi
        
    - name: Update xs-app.json (IDs específicos)
      run: |
        if [ -f "xs-app.json" ]; then
          jq 'walk(if type == "object" then 
                with_entries(if .key | test("^(id|name|service)$") then 
                  .value |= (if type == "string" then gsub("^actions$"; "actionsdev") else . end) 
                else . end) 
              else . end)' xs-app.json > tmp.json && mv tmp.json xs-app.json
          echo "xs-app.json updated"
        else
          echo "xs-app.json not found"
        fi
        
    - name: Update ui5-deploy.yaml (IDs específicos)
      run: |
        if [ -f "ui5-deploy.yaml" ]; then
          sed -i 's/\(id\|name\|service\): actions$/\1: actionsdev/' ui5-deploy.yaml
          sed -i 's/\(id\|name\|service\): "actions"$/\1: "actionsdev"/' ui5-deploy.yaml
          sed -i 's/archiveName: actions$/archiveName: actionsdev/' ui5-deploy.yaml
          echo "ui5-deploy.yaml updated"
        else
          echo "ui5-deploy.yaml not found"
        fi
        
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated update: Replaced 'actions' with 'actionsdev' in all config files (IDs, paths and routes)"
          git push
        fi
