name: Update mta.yaml on merge from dev to main

on:
  push:
    branches:
      - main

jobs:
  update-mta:
    # Solo ejecutar si el push vino de un merge de dev a main
    if: github.event.head_commit.message == 'Merge pull request #* from your-repo/dev' || github.event.head_commit.message == 'Merge branch 'dev' into main'
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Necesario para poder hacer push luego
        
    - name: Replace actions with actionsdev in mta.yaml
      run: |
        # Verificar si el archivo existe
        if [ -f "mta.yaml" ]; then
          # Hacer el reemplazo
          sed -i 's/actions/actionsdev/g' mta.yaml
          
          # Configurar git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Hacer commit y push de los cambios
          git add mta.yaml
          git commit -m "Automated update: replaced actions with actionsdev in mta.yaml"
          git push
        else
          echo "mta.yaml file not found. No changes made."
          exit 0
        fi
